# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"square": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://nbdev_test.github.io/nbdev_test/"

git_url = "https://github.com/nbdev_test/nbdev_test/tree/master/"

def custom_doc_links(name): return None
